---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest

- name: start nginx
  service:
    name: nginx
    state: started

- name: copying nginx file to server
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/default
  with_items:
    - "app.conf"

- name: Enable site
  shell: ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/
  ignore_errors: True
  tags: [nginx_config]

- name: node | nginx | Test Nginx
  shell: 'nginx -t || abort "Nginx: Configuration Test Failed"'
  notify:
  - reload nginx
